homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 60
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Moscow
  # Customization file
  customize: !include customize.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret conf_url
    
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: !secret nodered_url
    
# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret api_password
  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem


updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.memory_use_percent
      - sensor.cpu_temperature
      - sensor.disk_use_percent_home
      - sensor.disk_use_percent_homeubuntutm
      - sensor.processor_use
      - sensor.since_last_boot
      - sensor.transmission_active_torrents
      - sensor.transmission_down_speed
      - sensor.transmission_paused_torrents
      - sensor.transmission_status
      - sensor.transmission_total_torrents
      - sensor.transmission_up_speed

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

sensor: !include sensors.yaml

# Sensors
#sensor:
  # Weather prediction
#  - platform: yr

# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret key

light:
  - platform: xiaomi_miio
    name: Philips_living_room
    host: 192.168.1.160
    token: !secret token_lr
    model: philips.light.ceiling
  - platform: xiaomi_miio
    name: Philips_bed_room
    host: 192.168.1.180
    token: !secret token_br
    model: philips.light.ceiling
    
homekit:
  auto_start: false
  filter:
    include_domains:
      - light
      - switch
    exclude_entities:
      - light.gateway_light_34ce008c0fac
      - switch.plug_158d00011014b8
      - switch.wall_switch_left_158d00016d93d9
      - switch.wall_switch_right_158d00016d93d9

apple_tv:
  - host: 192.168.1.141
    login_id: !secret atv_login
    name: apple_tv
    start_off: true
    credentials: !secret atv_cr