- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'


- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: disk_use_percent
      arg: /home/ubuntu/tm
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot

- platform: transmission
  name: Transmission
  port: 9091
  host: 192.168.1.1
  username: !secret ???
  password: !secret ???
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
    - 'paused_torrents'
    - 'total_torrents'

- platform: template
  sensors:
    door_sensor_battery_158d0001a9c200:
      friendly_name: "Заряд датчика открытия двери"
      unit_of_measurement: '%'
      value_template: "{{ states.binary_sensor.door_window_sensor_158d0001a9c200.attributes. battery_level }}"
      icon_template: >-
        {% set battery_level = (states.binary_sensor.door_window_sensor_158d0001a9c200.attributes.battery_level)|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}
    motion_sensor_battery_158d0001b177e8:
      friendly_name: "Заряд датчика движения"
      unit_of_measurement: '%'
      value_template: "{{ states.binary_sensor.motion_sensor_158d0001b177e8.attributes. battery_level }}"
      icon_template: >-
        {% set battery_level = (states.binary_sensor.motion_sensor_158d0001b177e8.attributes.battery_level)|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}
    temperature_sensor_battery_158d00023764a1:
      friendly_name: "Заряд датчика температуры"
      unit_of_measurement: '%'
      value_template: "{{ states.sensor.temperature_158d00023764a1.attributes. battery_level }}"
      icon_template: >-
        {% set battery_level = (states.sensor.temperature_158d00023764a1.attributes.battery_level)|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}
    button_sensor_battery_158d0001aaab2d:
      friendly_name: "Заряд кнопки"
      unit_of_measurement: '%'
      value_template: "{{ states.binary_sensor.switch_158d0001aaab2d.attributes. battery_level }}"
      icon_template: >-
        {% set battery_level = (states.binary_sensor.switch_158d0001aaab2d.attributes.battery_level)|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}