- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'


- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: disk_use_percent
      arg: /home/ubuntu/tm
    - type: memory_use_percent
    - type: processor_use
    - type: since_last_boot
# +binary_sensor.door_window_sensor_158d0001106a52
# +binary_sensor.motion_sensor_158d000114fc7a
# +binary_sensor.motion_sensor_158d00016c3c5e
# sensor.illumination_158d00016c3c5e
# +binary_sensor.motion_sensor_158d00016dc907
# sensor.illumination_158d00016dc907
# +binary_sensor.switch_158d00010a7ba4
# +binary_sensor.switch_158d000215a8e9
# binary_sensor.wall_switch_both_158d000170fe8c
# binary_sensor.wall_switch_left_158d000170fe8c
# binary_sensor.wall_switch_right_158d000170fe8c
# binary_sensor.wall_switch_both_158d0001718ba6
# binary_sensor.wall_switch_left_158d0001718ba6
# binary_sensor.wall_switch_right_158d0001718ba6
# binary_sensor.water_leak_sensor_158d0002115cae
# sensor.illumination_34ce008c0fac
# sensor.humidity_158d0001178563
- platform: template
  sensors:
    door_sensor_battery_158d0001106a52:
      friendly_name: "Заряд датчика открытия двери"
      unit_of_measurement: '%'
      value_template: "{{ states.binary_sensor.door_window_sensor_158d0001106a52.attributes. battery_level }}"
      icon_template: >-
        {% set battery_level = (states.binary_sensor.door_window_sensor_158d0001106a52.attributes.battery_level)|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}
    motion_sensor_battery_158d000114fc7a:
      friendly_name: "Заряд датчика движения в спальне"
      unit_of_measurement: '%'
      value_template: "{{ states.binary_sensor.motion_sensor_158d000114fc7a.attributes. battery_level }}"
      icon_template: >-
        {% set battery_level = (states.binary_sensor.motion_sensor_158d000114fc7a.attributes.battery_level)|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}
    motion_sensor_battery_158d00016c3c5e:
      friendly_name: "Заряд датчика движения 1"
      unit_of_measurement: '%'
      value_template: "{{ states.binary_sensor.motion_sensor_158d00016c3c5e.attributes. battery_level }}"
      icon_template: >-
        {% set battery_level = (states.binary_sensor.motion_sensor_158d00016c3c5e.attributes.battery_level)|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}
    motion_sensor_battery_158d00016dc907:
      friendly_name: "Заряд датчика движения 2"
      unit_of_measurement: '%'
      value_template: "{{ states.binary_sensor.motion_sensor_158d00016dc907.attributes. battery_level }}"
      icon_template: >-
        {% set battery_level = (states.binary_sensor.motion_sensor_158d00016dc907.attributes.battery_level)|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}
    temperature_sensor_battery_158d00023764a1:
      friendly_name: "Заряд датчика температуры"
      unit_of_measurement: '%'
      value_template: "{{ states.sensor.temperature_158d00023764a1.attributes. battery_level }}"
      icon_template: >-
        {% set battery_level = (states.sensor.temperature_158d00023764a1.attributes.battery_level)|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}
    button_sensor_battery_158d00010a7ba4:
      friendly_name: "Заряд кнопки 1"
      unit_of_measurement: '%'
      value_template: "{{ states.binary_sensor.switch_158d00010a7ba4.attributes. battery_level }}"
      icon_template: >-
        {% set battery_level = (states.binary_sensor.switch_158d00010a7ba4.attributes.battery_level)|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}
    button_sensor_battery_158d000215a8e9:
      friendly_name: "Заряд кнопки 2"
      unit_of_measurement: '%'
      value_template: "{{ states.binary_sensor.switch_158d000215a8e9.attributes. battery_level }}"
      icon_template: >-
        {% set battery_level = (states.binary_sensor.switch_158d000215a8e9.attributes.battery_level)|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}